### ISSUE TITLE
Add ripgrep

### ISSUE THREAD

**Issue by isuruf** [conda-forge/conda-build-feedstock#102]
WARNING: Detecting which files contain PREFIX is slow, installing ripgrep makes it faster. 'conda install ripgrep'

**Comment by ocefpaf** [comment]
The version of `ripgrep` from defaults and `conda-forge` are wildly different. I did not checked the packages but that are they the same thing?

```
Loading channels: done
# Name                       Version           Build  Channel             
ripgrep                       0.10.0      hc07d326_0  pkgs/main           
ripgrep                       11.0.1               0  conda-forge
```

**Comment by ocefpaf** [comment]
I checked and they are from the same source, https://github.com/BurntSushi/ripgrep/, and the `0.10.0` is only two releases behind 11.0.1 ¯\_(ツ)_/¯

**Comment by dbast** [comment]
They changed the version schema ... so they are the same thing...  only two releases behind... and the conda-forge ripgrep is also available on windows :)
