### ISSUE TITLE
python-libarchive-c dependency missing

### ISSUE THREAD

**Issue by isuruf** [conda-forge/conda-build-feedstock#112]
cc @SylvainCorlay

**Comment by CJ-Wright** [comment]
This seems to be breaking the bot?
``OSError: /opt/conda/lib/libarchive.so: cannot open shared object file: No such file or directory``

**Comment by scopatz** [comment]
Is this still true?

**Comment by CJ-Wright** [comment]
It isn't breaking the bot

**Comment by gabm** [comment]
We are experiencing this as "cannot import libarchive" when using conda-build ... manually installing python-libarchive-c solves the problem for now...

**Comment by isuruf** [comment]
Fixed in #114
