### ISSUE TITLE
mark 3.18.10 as broken

### ISSUE THREAD

**Issue by beckermr** [conda-forge/conda-build-feedstock#118]
This version has a big performance drop in looking at links. The PR to fix this is here: https://github.com/conda/conda-build/pull/3782

It may be causing some builds to run out of CI time.

**Comment by CJ-Wright** [comment]
@conda-forge/core

**Comment by beckermr** [comment]
The bug fix for this was just merged. We might just wait for the next release if it will happen soon. 

What is the ETA @marcelotrevisani ?

**Comment by chrisburr** [comment]
https://github.com/conda/conda-build/pull/3782 is buggy (see https://github.com/conda/conda-build/pull/3782#pullrequestreview-305292501).

I don't have time to make a fixed PR today so I'm happy for someone else to. If not, I'll try to do it tomorrow.

**Comment by beckermr** [comment]
Is it buggy or just not the simplest way to do things? As far as I can see, pre-compiling a regex should be fine.

**Comment by looooo** [comment]
https://github.com/conda/conda-build/issues/3775#issuecomment-546350502

please mark 3.18.10 as broken if no new release is coming soon.

**Comment by beckermr** [comment]
closing since we had a new release
