### ISSUE TITLE
Is requirement on conda < 4.3 required?

### ISSUE THREAD

**Issue by jjhelmus** [conda-forge/conda-build-feedstock#12]
The recipe lists the dependency on conda as `conda  >=4.1,<4.3`.  This prevents conda-build 2.1.2 in an environment with conda 4.3.  Is this really necessary, or can this requirement be relaxed?

I noticed this as `noarch: python` packages require (or at least seem to) conda 4.3 and therefore such packages cannot currently be built and tested with conda-build.  Specifically, if such a package is build the following error is raised during the test:

```
TEST START: imagesize-0.7.1-py_60
Deleting work directory, /Users/jhelmus/anaconda/conda-bld/recipe_1485276670901/work/imagesize-0.7.1
updating index in: /Users/jhelmus/anaconda/conda-bld/osx-64
updating index in: /Users/jhelmus/anaconda/conda-bld/noarch

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    imagesize-0.7.1            |            py_60           5 KB  local

The following NEW packages will be INSTALLED:

    imagesize: 0.7.1-py_60 local
    openssl:   1.0.2j-0    defaults
    python:    3.5.2-0     defaults
    readline:  6.2-2       defaults
    sqlite:    3.13.0-0    defaults
    tk:        8.5.18-0    defaults
    xz:        5.2.2-1     defaults
    zlib:      1.2.8-3     defaults

Installing local::imagesize-0.7.1-py_60 requires a minimum conda version of 4.3.
```

**Comment by msarahan** [comment]
With conda-build 2.1.2, this can be relaxed to >=4.1

**Comment by jjhelmus** [comment]
I'll submit a PR shortly.

**Comment by jakirkham** [comment]
Does that mean `conda` 4.3  is supported? Also what is the status w.r.t `conda` 4.4?

**Comment by msarahan** [comment]
https://github.com/conda/conda-build/releases/tag/2.1.2

no comment on 4.4 yet.  I'll add that to my test matrix when it seems closer to release.
