### ISSUE TITLE
@conda-forge-admin please rerender

### ISSUE THREAD

**Issue by marscher** [conda-forge/conda-build-feedstock#208]

**Comment by jakirkham** [comment]
Is there some context on why this is needed?

**Comment by marscher** [comment]
The idea was to enable the Python 3.12 build

**Comment by kenodegard** [comment]
conda-build won't officially support Python 3.12 until next year, see https://github.com/conda/conda-build/issues/4997 and https://github.com/conda/conda-build/pull/4998
