### ISSUE TITLE
Pin py-lief to >=0.14 ?

### ISSUE THREAD

**Issue by ColemanTom** [conda-forge/conda-build-feedstock#224]
### Comment:

In conda-build v24.3.0, the code was updated to use liblief 0.14. It is possible to install the current version of conda build whilst having an older version of liblief installed, which then can cause conda-build to not work. I would suggest pinning py-lief to >=0.14 to ensure only the correct versions are installed.

Of course, there are [memory issues with liblief=0.14](https://github.com/lief-project/LIEF/issues/1039), but I think it is still a requirement for 24.3.0 conda-build.

**Comment by mbargull** [comment]
`conda-build=24.3` was updated with support for LIEF 0.14 but still supports older versions of LIEF.
The memory issue introduced in that process has been fixed in `conda-build=24.5.1` which should be available on conda-forge shortly.
