### ISSUE TITLE
Tick version to 1.21.11

### ISSUE THREAD

**Issue by pmlandwehr** [conda-forge/conda-build-feedstock#4]
Hey-lo,

Can we get this version ticked to `1.21.11`?

**Comment by jakirkham** [comment]
👍 Though I'm not sure what the state is w.r.t. to entry points. Is this something we can achieve, @msarahan, or should we hold off on updates? I really would like to avoid the messy logging business we had before if possible.

**Comment by msarahan** [comment]
You can build it.  As is, Linux and Mac should work perfectly.  Windows entry points won't work at all, though, until people are using conda >=4.2.3.

If anyone wants to patch this to use distutils + conda entry points for Windows, that's a path forward.  Otherwise, this is current on defaults.  Why does it need to be built here, also?

**Comment by pmlandwehr** [comment]
My only issue is that I use `conda-forge` as default these days. I can certainly set up to use `defaults` as default, I'd just prefer to be uniform.

**Comment by msarahan** [comment]
That's a great reason, but I think we pulled all of the conda-forge packages for conda-build after discovering the dysfunctional entry points - you should be able to have defaults be a lower priority channel and still get current conda-build, I think.

**Comment by pmlandwehr** [comment]
Hmm; I have defaults as a lower priority channel but `conda-build` wasn't updating onto it with `conda update --all` Just did a forced `conda install -c defaults conda-forge` to get the latest defaults build, but if there's other conda-forge build that have been forcibly removed I suspect I'll have to call them out one at a time as well.

It looks that there's [still an anaconda.org entry for [conda-forge/conda-build](https://anaconda.org/conda-forge/conda-build) even though it has no files. Maybe we should kill it?

**Comment by jakirkham** [comment]
To control channel priority just edit `.condarc`. Basically I just put whatever I want first (e.g. `conda-forge`) and then `defaults` after.

It's ok that the stub page for `conda-build` is there. We just have purged the packages from it.

**Comment by jakirkham** [comment]
So we are on `conda-build` 2.1.1 now, which is latest. For the reasons mentioned, we didn't package this version of 1.x, but it is irrelevant now.
