### ISSUE TITLE
Package py-lief in conda-forge

### ISSUE THREAD

**Issue by isuruf** [conda-forge/conda-build-feedstock#85]

**Comment by mingwandroid** [comment]
BTW, our py-lief packages contain no dist info directories which is unfortunate. Need to figure that out. AFAIR pybind11 is used here. Suggestions or help welcome.

**Comment by ocefpaf** [comment]
@isuruf looks like we have py-lief in https://github.com/conda-forge/lief-feedstock, can we close this one?
